    name: GitHub Classroom Workflow

    on:
      push:
        paths:
          - 'dia_anterior.py'
          - '.github/classroom/autograding.json'
          - '.github/workflows/classroom.yml'

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: education/autograding@v1
        env:
          LANG: C.UTF-8
